### ISSUE TITLE
Wildcard Config Support

### ISSUE THREAD

**Issue by NielsPilgaard** [Lothrazar/HostileOres#1]
Relay from Twitter:

Please allow defining all blocks from a mod with `mod:*` in the config files :)

**Comment by Lothrazar** [comment]
Hey, sorry i didnt see this when you posted it.  Probably too late for your pack but its in the latest update.  I just copied the formatter that cyclic uses so you can use either mod:* or even cyclicmagic:*_ore 


https://minecraft.curseforge.com/projects/anger-management/files/2688252

**Comment by NielsPilgaard** [comment]
Sweet, thanks!
