### ISSUE TITLE
Cant access config

### ISSUE THREAD

**Issue by Niosquare** [Lothrazar/HostileOres#4]
Minecraft version & Mod Version: 1.14.4

Single player or Server: Single Player

Describe problem (what you were doing / what happened): Can't access config file

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

I've been trying to access it to no avail (I'm kinda new to the config file thing)

**Comment by Lothrazar** [comment]
what happens when you open it?  after you run the game once does it show up in /config/ folder?

**Comment by Niosquare** [comment]
> what happens when you open it? after you run the game once does it show up in /config/ folder?

i'm so dumb. What's your mods name in config folder?

**Comment by Niosquare** [comment]
I checked the whole config folder, couldn't find it

**Comment by Lothrazar** [comment]
OH right you are in 1.14 , that version doesnt have the config yet, it has to be remade for the new .toml format. coming soon tho!

**Comment by Niosquare** [comment]
> OH right you are in 1.14 , that version doesnt have the config yet, it has to be remade for the new .toml format. coming soon tho!

Awwww ; ( Thats fine though. Can't wait! Great mod by the way. Have a good night/day!

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/anger-management/files/2763771

**Comment by Niosquare** [comment]
Thank you so much great mod :)
